[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"
authors = ["hongpai <hopex40@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
